# Generated by Django 5.0.4 on 2024-07-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
