# Generated by Django 5.0.4 on 2024-07-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tictactoe_app', '0002_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='         ', max_length=9)),
                ('current_turn', models.CharField(choices=[('X', 'Player X'), ('O', 'Player O'), (' ', 'Empty')], default='X', max_length=1)),
                ('winner', models.CharField(choices=[('X', 'Player X'), ('O', 'Player O'), (' ', 'Empty')], default=' ', max_length=1)),
                ('is_draw', models.BooleanField(default=False)),
            ],
        ),
    ]
